### PR TITLE
Resource timing

### PR DESCRIPTION
**Pull request by 3rd-Eden**
As per title, this PR adds the follow features to the project:

1. Use Resource Timing API to get more detailed timing information about the start/end of the request.
2. Use the same API to more accurately guess the loadEnd by including resources that are loaded during the page.
3. Wait with the execution of the navigated callback, so we have `delay` amount of ms to wait for more resources to be loaded.
4. Corrected the base metrics to have `loadEventStart` receive the same timing as `domComplete` as that is when the loading starts. 
5. Added test coverage generation

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
@Verkurkie ^ this might be of interest to you as well.

**Comment by 3rd-Eden** [comment]
The only change that is left to do is adding an additional event in the `next` client, that is executed before/after the `getInitialProps` is called of a page. So we can get more accurate information on when the response actually ended, as just downloading the JavaScript payload is just a small part of it.

**Comment by Verkurkie** [comment]
Exciting improvement! Looks good to me! Would be interesting to watch things in Chrome performance tab to see where the responseEnd value ends up in relation to the network/js/paint events ...

**Comment by 3rd-Eden** [comment]
@kinetifex Forgot to update dependencies locally, tests are updated to reflect this and a new `package-lock` has been generated. - I'll add Travis-CI as well to ensure that these issues are caught early on.

**Pull request merged**
